### ISSUE TITLE
I'd like to publish this to maven

### ISSUE THREAD

**Issue by ririw** [rschreijer/s2-geometry-library-java#3]
Is that ok with you?

Here are a few questions:
- Of resonable quality (you're a better judge of this than I am)
- Do you mind if I publish it to maven?
- Do you want me to push the changes back in, they'll include:
  -  porting from ant to maven
  - checking library versions and pulling them from maven as well

**Comment by ririw** [comment]
And also changing some documentation to be compatible with javadoc's HTML format

**Comment by rschreijer** [comment]
Yeah you can do whatever you want with this code! Just Fork it and go ahaead.

I just migrated this lib from googlecode before they shut it down, and I wasn't planning to maintaining it here. I'm OK though if you prefer making PRs and start advancing this repository, but maybe do a search on github first to see if someone already did the things you want to do.

Happy coding!
--R

**Comment by rschreijer** [comment]
https://github.com/pwheimann/s2-geometry-library-java

**Comment by ririw** [comment]
Ah thanks!
